### ISSUE TITLE
Local edit sending multiple times

### ISSUE THREAD

**Issue by joshms123** [tms88/mudmixer#1]
Hi there,
I have tested this on 2 muds (chatmud and one other).
When editing a verb, if you save multiple times, it programs the verb once; however, if you close the notepad window and edit the same verb again, saving will program the verb twice. Reopening it again will program it three times, and so on.
If you need any extra info, i'm happy to provide.
MUDMixer v1.0.0
NodeJS v14.16.0
Thanks for any help in advanced.

**Comment by storsletten** [comment]
Oh whoops. Yeah that was a not so nice oversight on my part. Thanks for letting me know! I believe it's fixed now in the latest commit, but if not please let me know!

**Comment by joshms123** [comment]
Seems to work, thanks!
