### ISSUE TITLE
Issues with chatpack

### ISSUE THREAD

**Issue by joshms123** [tms88/mudmixer#2]
Hi there,
This isn't exactly a bug, but i'm struggling to get chatpack to work over mudmixer with chatmud.
When I connect to a session, I do get the MCP message now but i'm wondering if it might break if it goes to the connection that isn't chatmud first. Maybe there could be a way to spesify the connection when entering the session ID to connect to?
Also, I manually echoed the MCP message to chatpack once I was on the right connection and I did get the message saying thanks for using chatpack; however, sounds still do not play. I do see the #$#json messages, but i'm guessing it may be an issue on negotiation.
I am happy to give info where needed.
Thanks,
Josh.

**Comment by storsletten** [comment]
Hello hello!
My plan is to add client profiles, so as an alternative to connecting to a session you can connect to a client profile. A client profile will include info about which session to use, what kind of EOL sequence to use, etc. Could definitely throw in an option there to set which connection to focus on when connecting too.

As for MCP, the way it works is that each client and server perform their own independent negotiation with MX. The advantage of this is that MX can operate as a proxy between clients and servers, and make sure simpleedit requests and other things can be safely relayed between endpoints that don't share the same auth keys. A disadvantage is that clients can't perform MCP negotiation directly with servers on the other side.
If you have a specific MCP negotiation that needs to take place, then you can create a middleware to facilitate it. I'll have to give the docs a lot more love though to make it easier for people to do that.
I'm also willing to consider adding support for Chatpack in the default middleware, but then I would need to know more about what accommodations are needed specificly.
Let me know what you think.

**Comment by joshms123** [comment]
Hi there,
The client profile idea sounds amazing and useful!
I am happy to assist in providing information for the chatpack middleware, just no clue how to make it my self.
It does use JSON in places, I think someone did mention GMCP? But i'd have to check.
Thanks for any help in advanced,
Josh.

**Comment by storsletten** [comment]
Yeah. I'll need to add support for GMCP, and I also realize that it would be super useful to simply link one client and one server together in terms of OOB/IAC messages. The way I envision this to work is that once you link a client and server together with this special kind of metadata link, then those two devices won't share their OOB messages with any other devices in the mix. This would make it possible for the client to switch to other connections without breaking the metadata link with a specific server connection. These changes will probably take some time to implement though, but I'll make it a priority.
Thank you so much for your valuable feedback! It's always appreciated!
